hash-format = "sha256"

[[files]]
file = "mods/appleskin.jar"

[[files]]
file = "mods/better-hand-bobbing.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/craftmine-fixes.jar"

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/forcecloseloadingscreen.jar"

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/nochatreports.jar"

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/player-relocks.jar"

[[files]]
file = "mods/sodium-extra.jar"

[[files]]
file = "mods/sodium.jar"

[[files]]
file = "mods/tiny-item-animations.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
metafile = true
