name = "Better CraftMine"
author = "LittleChest"
version = "25.14.1"
description = "25w14craftmine, but bug fixes and QoL features!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.16.12"
minecraft = "25w14craftmine"

[options]
no-internal-hashes = true
