name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest release version
        id: latest-release
        uses: fangqiuming/latest-release-version@v1.1.1

      - name: Install Packwiz
        run: |
          sudo curl -L https://github.com/REVanillaW/packwiz/releases/download/CI/packwiz-linux-amd64 -o /bin/packwiz
          sudo chmod +x /bin/packwiz
          packwiz refresh --build

      - name: Export Modrinth modpack
        run: |
          packwiz rehash sha512
          packwiz modrinth export

      - name: Upload Modrinth modpack
        uses: actions/upload-artifact@v4
        with:
          name: Modrinth
          path: Better CraftMine-*.mrpack
          if-no-files-found: error

      - name: Export CurseForge modpack
        run: |
          packwiz rehash sha1
          packwiz curseforge export

      - name: Upload CurseForge modpack
        uses: actions/upload-artifact@v4
        with:
          name: CurseForge
          path: Better CraftMine-*.zip
          if-no-files-found: error

      - name: Update mods
        run: |
          echo "" > .packwizignore
          packwiz refresh --build
          packwiz update --all -y | tee UPDATE_LOG
          if [ `grep -c "All files are up to date!" UPDATE_LOG` -ne "1" ]; then echo "::warning title=Update Available::Some mods can be updated."; fi
